name: conventional-pr
on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - edited
      - synchronize
jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # check for the most recent release: https://github.com/CondeNast/conventional-pull-request-action/releases
      - uses: CondeNast/conventional-pull-request-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitTitleMatch: "false" 
          ignoreCommits: "true"
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack notify prepare
        id: slack-notify-prepare
        if: steps.release.outputs.new_release_published == 'true'
        run: |
          LAST_RELEASE_VERSION=${{ steps.release.outputs.last_release_version }}
          NEW_RELEASE_VERSION=${{ steps.release.outputs.new_release_version }}
          if [[ ! -z LAST_RELEASE_VERSION ]]
          then
            last=(`echo $LAST_RELEASE_VERSION | tr '.' ' '`)
            new=(`echo $NEW_RELEASE_VERSION | tr '.' ' '`)
            last_major=${last[0]}
            last_minor=${last[1]}
            new_major=${new[0]}
            new_minor=${new[1]}
            if [[  $new_minor -gt $last_minor || $new_major -gt $last_major ]]
            then
              echo "SLACK_SHOULD_NOTIFY=true" >> $GITHUB_ENV
            fi
          fi

      - name: echo
        run: |
          echo $SLACK_SHOULD_NOTIFY

      - name: if check
        if : $SLACK_SHOULD_NOTIFY="true"
        run: | 
          echo "If is true"


      