name: Release
on:
  push:
    branches:
      - master
      - main
env: 
  SLACK_SHOULD_NOTIFY: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Slack message prepare
        id: slack-message
        run: |
          if [$LAST_RELEASE_VERSION]; then 
            previous=(`echo $LAST_RELEASE_VERSION | tr '.' ' '`)
            next=(`echo $NEW_RELEASE_VERSION | tr '.' ' '`)
            previous_major=${previous[0]}
            previous_minor=${previous[1]}
            next_major=${next[0]}
            next_minor=${next[1]}

            if [[ "$next_major" -gt "$previous_major"  ||  "$next_minor" -gt "$previous_major" ] ]; then
              SLACK_SHOULD_NOTIFY=true
            done
          done
          fi
        env: 
          LAST_RELEASE_VERSION: ${{ steps.release.outputs.last_release_version }}
          NEW_RELEASE_VERSION: ${{ steps.release.outputs.new_release_version }}

      - name: Test
        id: Test
        if : $SLACK_SHOULD_NOTIFY
        run : |
          echo "Hello world"