name: Release
on:
  push:
    branches:
      - master
      - main
env: 
  SLACK_SHOULD_NOTIFY: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Slack message prepare
        id: slack-message
        run: |
          LAST_RELEASE_VERSION=${{ steps.release.outputs.last_release_version }}
          NEW_RELEASE_VERSION=${{ steps.release.outputs.new_release_version }}
          if [[ ! -z LAST_RELEASE_VERSION ]]
          then
            last=(`echo $LAST_RELEASE_VERSION | tr '.' ' '`)
            new=(`echo $NEW_RELEASE_VERSION | tr '.' ' '`)
            last_major=${last[0]}
            last_minor=${last[1]}
            new_major=${new[0]}
            new_minor=${new[1]}
            if [[  $new_minor -gt $last_minor || $new_major -gt $last_major ]]
            then
              echo "SLACK_SHOULD_NOTIFY=true" >> $GITHUB_ENV
            fi
          fi
        env: 
          LAST_RELEASE_VERSION: ${{ steps.release.outputs.last_release_version }}
          NEW_RELEASE_VERSION: ${{ steps.release.outputs.new_release_version }}

      - name: Test
        id: Test
        if : $SLACK_SHOULD_NOTIFY
        run : |
          echo "Hello world"